spring.application.name=TradeForge

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/Trading
spring.datasource.username=root
spring.datasource.password= ${PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Integrate Coingecko API
coingecko.base-url= ${COINGECKO_URL}

#Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY}
razorpay.key.secret=${RAZORPAY_SECRET}
razorpay.callback.url=${RAZORPAY_CALLBACK_URL}


#Stripe Configuration
stripe.key.id=${STRIPE_KEY}
stripe.key.secret=${STRIPE_SECRET}
stripe.success.url=${STRIPE_SUCCESS_URL}
stripe.cancel.url=${STRIPE_CANCEL_URL}